---
kind: pipeline
type: docker
name: Production

steps:
- name: Build Dockerfile
  image: alpine
  commands:
    - apk update && apk add bash curl grep jq sed
    - ./build.sh

- name: Build & Publish Image
  image: plugins/docker
  settings:
    repo: fbrinker/tileboard
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - main

---
kind: pipeline
type: docker
name: Development

steps:
- name: Check for changes in master branch
  image: alpine
  commands:
    - apk update && apk add bash curl grep jq sed
    - ./check-master-for-changes.sh

- name: Build & Publish Development Image
  image: plugins/docker
  settings:
    repo: fbrinker/tileboard
    dockerfile: Dockerfile.nightly
    target: dev
    tags: dev
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: Build & Publish Nightly Image
  image: plugins/docker
  settings:
    repo: fbrinker/tileboard
    dockerfile: Dockerfile.nightly
    target: nightly
    tags: nightly
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - main
