---
kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: fbrinker/tileboard
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
      
trigger:
  branch:
  - master