---
kind: pipeline
type: docker
name: production

steps:
- name: Build Dockerfile
  image: alpine
  commands:
    - apk update && apk add bash curl grep jq sed
    - ./build.sh

- name: Build & Publish Image
  image: plugins/docker
  settings:
    repo: fbrinker/tileboard
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master