---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: alpine
  commands:
    - apk update && apk add bash grep sed curl unzip jq
    - chmod +x ./build.sh
    - ./build.sh

- name: docker
  image: plugins/docker
  settings:
    repo: fbrinker/tileboard
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master